version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "maven-enforcer-plugin"
        versions: [">=3.1"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
