sudo: required
dist: trusty
language: c

before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats libedit-dev libedit2 openjdk-7-jdk openjdk-8-jdk maven

before_script:
  - jdk_switcher use $JDK

compiler:
  - clang
  - gcc

env:
  - JDK=openjdk7
  - JDK=openjdk8

script:
  - make clean bats T_LIBS="JavaEditline JavaReadline JavaGetline" CC=$CC
  - mvn clean site install

