name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        jdk: ['7', '8', '11', '17', '21']
        cc: [gcc, clang]
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.jdk }}
        java-package: jdk
    - name: Install dependencies
      run: |
         sudo apt-get update -qq
         sudo apt-get install -qq bats libedit-dev libedit2
    - name: Build
      run: |
         make clean bats T_LIBS="JavaEditline JavaReadline JavaGetline" CC=${{ matrix.cc }}
         mvn clean site install
